### ISSUE TITLE
Momentum System

### ISSUE THREAD

**Issue by BenicioLadines** [StudioAspen/Aspen2024-2025#31]
You should have some number go up when you kill enemies quickly.

Maybe you have a certain amount of time between each kill and it gets shorter the higher ur momentum score goes! We don't need to worry about what it does yet but I'm assuming there'll be some event when the score goes up (you get a kill) and when it resets

**Comment by samsonahh** [comment]
Task Breakdown:

- [x] Create a new C# script class called MomentumSystem
- [x] Make the following variables
1. `private int momentum`: your momentum count
2. `private float timer`: timer that goes up between each kill
3. `[SerializeField] private float baseTimeBetween`: the starting max duration between kills
4. `[SerializeField] private float timeBetweenMultiplier`: will be a number less than 1 that will multiply on top of the variable `timeBetween`
5. `private float timeBetween`: current time between at that momentum after multiplier calculation
- [x] Make the function `public void AddMomentum()` so that other classes will be able to add to the momentum (and reset the timer)
1. increment `momentum`
2. set `timer` to 0
3. multiply `timeBetween` with `timeBetweenMultiplier`, this will become your new `timeBetween`
- [x] Make the function `private void Reset()` to be called once your timer runs out for killing the next enemy
1. set `timer` to 0
2. set `timeBetween` back to the `baseTimeBetween`
3. set `momentum` back to 0
4. [x] Make sure your `timeBetween` starts at `baseTimeBetween`
- [x] In update:
1. increment the `timer` by `Time.deltaTime` if momentum is larger than 0
2. check if the `timer` is larger than `timeBetween`, if so call `Reset()`

Tips:
- Use `Debug.Log("")` to debug and test your code
- In update, assign a key to press to simulate adding to the momentum because we dont have an event that fires when the player gets a kill yet
- Search things up
